name: Projet Asmtariste - CI/CD

on:
  push:
    branches: [ staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Install Angular CLI
      run: npm install -g @angular/cli
    
    - name: Run unit tests
      run: ng test --watch=false --browsers=ChromeHeadless

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Install Angular CLI
      run: npm install -g @angular/cli
    
    - name: Build Angular app
      run: ng build --configuration production
    
    - name: Deploy to Staging
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: dist/dashboard/browser/
        remoteDir: /dashboard-staging.asmtariste.fr/